# Site settings
#baseurl = "http://localhost/ask-public/public/"
baseurl = "https://staticdev.scholarsportal.info/ask-public/"
title = "Ask A Librarian"
languageCode = "en-us"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Ask A Librarian"
	description = "Ask a Librarian is a collaborative virtual reference service that connects students, faculty and researchers from participating libraries across Ontario with real-time research assistance through chat in English and French."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "chat@scholarsportal.info"

    # Link custom assets relative to /static
    custom_css = ["css/custom.css"]
    custom_js  = []
	favicon    = "favicon.ico"

	# Possibility to disable external/additional fonts
	# Exception: Fontawesome
	disableFonts = false

	# 404 error customization
	[params.error404]
	heading = "Page couldn't be found"
	text = "Please visit [this page](/)"


	# Navigation
	[params.navigation]
		brand = "Ask A Librarian"
		services = "Benefits"
		about = "Features"
		portfolio = "Statistics"
		team = "Team"
		clients_list = "Participants"
		pricing = "Pricing"
		faq = "FAQ"
		contact = "Contact"
		img = "logo_notext.png"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "#"
    #    name = ""
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "https://spotdocs.scholarsportal.info/display/ASK"
        name = "Login <i class=\"fa fa-external-link\" aria-hidden=\"true\"></i>"
        weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Ask a Librarian"
		subtitle = "Connecting users with research assistance through chat."
		buttonText = "Tell me more"

		[[params.hero.logo]]
			img = "logo.png"


	[params.headtext]
	enable = true
		description = "Ask a Librarian is a collaborative virtual reference service that connects students, faculty and researchers from participating libraries across Ontario with real-time research assistance through chat in English and French."

	# Benefits section
	[params.services]
    enable = true
		title = "Benefits"
		subtitle = ""

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-clock-o"
                title = "Extended hours"
                description = "Ask a Librarian is available 67 hours per week during the academic year, including on evenings and weekends."

			[[params.services.row.list]]
                icon = "fa-map-marker"
                title = "Available anywhere"
                description = "Ask a Librarian provides online, on-demand assistance from the library website, allowing users to get help immediately no matter where they are."

            [[params.services.row.list]]
                icon = "fa-users"
                title = "Expert staff"
                description = "Our expert staff are trained to provide local, trustworthy answers to library- and research-related questions."

			[[params.services.row.list]]
                icon = "fa-language"
                title = "Bilingual service"
                description = "Chat support is available in both English and French during all service hours."

    # Features section
	[params.about]
    enable = true
		title = "Features"
		subtitle = ""
		endpoint = "[<br>Contact Us!](#contact)"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.

		[[params.about.events]]
			img = "libh3lp.png"
			title = "LibraryH3lp"
			description = "Ask a Librarian is powered by Nub Games’ [LibraryH3lp](https://libraryh3lp.com/), a flexible, scalable chat platform designed for libraries. LibraryH3lp has a simple, user-friendly interface, ample customization options, and a responsive customer support team. The platform has proactive chat functionality and offers unlimited knowledge bases and an optional add-on for text messaging."

		[[params.about.events]]
			img = ""
			title = "Training"
			description = "Scholars Portal offers a comprehensive training program for new chat operators. Sessions include an orientation to the service, hands-on training on the chat platform, a review of best practices for virtual reference and online communication, and an introduction to service policies and procedures."

		[[params.about.events]]
			img = ""
			title = "Support"
			description = "The Ask a Librarian service is coordinated by a designated Scholars Portal librarian, who supports local chat coordinators and manages daily operations, including scheduling, training, communications, assessment, and user support. The coordinator also maintains the chat software, liaises with Nub Games, and hires and supervises student and casual workers who contribute to the service."

		[[params.about.events]]
			img = ""
			title = "Impact"
			description = "Participating libraries can track local service usage and operator activity through statistical reports available in the LibraryH3lp admin console. Exit survey results are also available to evaluate user satisfaction and service quality. The Ask a Librarian coordinator can assist with statistical tracking, custom reports, and assessment and evaluation projects."


	# Use Cases section
	[params.portfolio]
    enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more information take a look at the README.
		title = "Chat by the Numbers"
		subtitle = ""

		[params.portfolio.modal]
			client = "Client"
			date = "Date"
			category = "Category"
			buttonText = "Close"

    # Pricing section - see layouts/partials/pricing.html
    [params.pricing]
    	enable = false
    	title = "Pricing"
    	subtitle = ""

   	# FAQ section
   	[params.faq]
   		enable = true
   		title = "FAQ"
   		subtitle = "Frequently Asked Questions"

   		[[params.faq.questions]]
   		question = "How can libraries join Ask a Librarian?"
   		answer = "Additional information about Ask a Librarian is available by [contacting us](#contact). Libraries interested in joining Ask a Librarian are invited to contact [ocul@ocul.on.ca](mailto:ocul@ocul.on.ca)."
		id = "01"

		[[params.faq.questions]]
   		question = "How does Ask a Librarian work?"
   		answer = "Users enter the chat service through graphic chat buttons or pop-up chat invitations located across their library’s website. Clicking on the chat button or invitation launches a chat window, where the user can enter their question. Ask a Librarian staff answer incoming chats using [LibraryH3lp’s](https://libraryh3lp.com/) chat software and documentation on [the Ask wiki space](https://spotdocs.scholarsportal.info/display/ASK). When the service is closed, questions can be sent to the home library by email, or the user can be routed to a specific webpage. <br><br> The service is open 67 hours per week, and multiple operators are scheduled for each shift to handle demand. During all hours of service, chat is available in both English and French."
		id = "02"

		[[params.faq.questions]]
   		question = "Who staffs Ask a Librarian?"
   		answer = "Ask a Librarian is staffed by librarians and library staff from participating Ontario libraries. During evening and weekend hours, trained students or recent graduates of Masters-level programs in library or information studies also staff the service."
		id = "03"

   		[[params.faq.questions]]
   		question = "What information are users asked to provide?"
   		answer = "At the beginning of the chat session, Ask a Librarian users are asked to indicate their name and level of study, in order for staff to provide personalized research assistance. Answering these questions is voluntary, and patrons can choose to use the service anonymously. Staff may request the patron’s email address during a chat session in order to follow-up on a research request, but users are not obligated to provide it."
		id = "04"

   		[[params.faq.questions]]
   		question = "What is Ask a Librarian’s privacy policy?"
   		answer = "OCUL, your university library, and all Ask a Librarian staff respect your privacy. User data can only be accessed by Scholars Portal staff and by designated administrators from participating libraries. Information provided while using the service is collected primarily for statistical reporting to the OCUL board of directors, funding agencies, and your local institution. Data collected through the service may also be used for research purposes, but privacy and anonymity of users will be ensured. Personal information that you provide in order to use Scholars Portal services will be protected in accordance with FIPPA, the Freedom of Information and Protection of Privacy Act. We will not disclose any personal data we collect from you to any party in a manner that would identify you, except to fulfill your service request or where required by law."
		id = "05"

   		[[params.faq.questions]]
   		question = "I would like to use Ask a Librarian data for a research project. How can I get access?"
   		answer = "OCUL’s Virtual Reference Steering Committee is supportive of research involving virtual reference and recognizes its value to the library community. Chat data may be made available to researchers at OCUL member institutions for the purposes of research leading to dissemination of results. Data used for research purposes is anonymized to maintain user privacy, in accordance with Ask a Librarian’s privacy policy. For full details, please refer to the Ask a Librarian [data access policy and request form](https://docs.google.com/forms/d/e/1FAIpQLSeJLotFlu2JXKJXWFrjJ0SlWkNRU_NffevArnpPJ-pUyfkfTA/viewform?c=0&w=1)."
		id = "06"


	# Team section (disabled)
	[params.team]
    enable = false
		title = ""
		subtitle = ""
		description = ""

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = ""
			name = ""
			position = ""
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

	# Partners section
    [params.clients_list]
        enable = true
        title="Participants"
        subtitle=""

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.

    	[[params.clients]]
    		logo = "Algoma.jpg"
    		link = "http://library.algomau.ca/main/"
    		alt = "Algoma University"

		[[params.clients]]
    		logo = "Brock.png"
    		link = "https://brocku.ca/library/"
    		alt = "Brock University"

		[[params.clients]]
    		logo = "Carleton.jpg"
    		link = "https://library.carleton.ca/"
    		alt = "Carleton University"

		[[params.clients]]
    		logo = "Guelph.jpg"
    		link = "http://www.lib.uoguelph.ca/"
    		alt = "University of Guelph"

		[[params.clients]]
    		logo = "GuelphHumber.jpg"
    		link = "https://www.guelphhumber.ca/library"
    		alt = "University of Guelph-Humber"

		[[params.clients]]
    		logo = "Lakehead.png"
    		link = "https://library.lakeheadu.ca/"
    		alt = "Lakehead University"

		[[params.clients]]
    		logo = "Laurentian.jpg"
    		link = "https://laurentian.ca/library"
    		alt = "Laurentian University"

		[[params.clients]]
    		logo = "McMaster.jpg"
    		link = "http://library.mcmaster.ca/"
    		alt = "McMaster University"

		[[params.clients]]
    		logo = "OCAD.png"
    		link = "http://www.ocadu.ca/services/Library.htm"
    		alt = "OCAD University"

		[[params.clients]]
    		logo = "UOIT.png"
    		link = "https://uoit.ca/sites/library/"
    		alt = "University of Ontario Institute of Technology"

		[[params.clients]]
    		logo = "Ottawa.png"
    		link = "https://biblio.uottawa.ca/"
    		alt = "University of Ottawa"

		[[params.clients]]
    		logo = "Ryerson.png"
    		link = "http://library.ryerson.ca/"
    		alt = "Ryerson University"

		[[params.clients]]
    		logo = "SaintPaul.png"
    		link = "https://ustpaul.ca/jean-leon-allie-omi-library.php"
    		alt = "Saint Paul University"

		[[params.clients]]
    		logo = "Toronto.png"
    		link = "https://library.utoronto.ca/"
    		alt = "University of Toronto"

		[[params.clients]]
    		logo = "Western.png"
    		link = "https://www.lib.uwo.ca/"
    		alt = "Western University"

		[[params.clients]]
    		logo = "York.png"
    		link = "https://www.library.yorku.ca/web/"
    		alt = "York University"

	# Contact section
	[params.contact]
    enable = true
		title = "Contact us"
		subtitle  = "Get In Touch!"
		buttonText = "Send message"

		[params.contact.captcha]
    	#sitekey = ""

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Organization *"
			warning = "Please enter your organization."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
    enable = true
		copyright = "&copy; Ontario Council of University Libraries"
    secondcopyright = "Scholars Portal"
		logo = "ocul.png"
    secondlogo = "sp.png"
		link = "http://ocul.on.ca"
    secondlink = "http://scholarsportal.info/"

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/scholarsportal"
			alt = "twitter"
